### ISSUE TITLE
Get the stuff back up

### ISSUE THREAD

**Issue by catfoolyou** [FCPSOff/fcpsoff.github.io#2]
You need to stop giving into their demands and just keep your stuff up. If it gets patched, just try to fix it. 
What are they gonna do about it?

**Comment by CaenJones** [comment]
We already receive punishment in our school district for every time we update the site. We try to offer a best-effort time frame and move forward if we receive no response. This is to ensure fair practice on both sides and to keep channels open for other issues to come.

**Comment by CaenJones** [comment]
Is there a specific item that you want to know more about?

**Comment by catfoolyou** [comment]
Yes, the applocker stuff. Also how do they know that you did it and what is the reason they punished you? i.e. what rules are they citing? They can't just screw you over without any particular reason, and asking for this kind of stuff when they do get you really gives them a pain in the ass.

**Comment by catfoolyou** [comment]
I've gotten out of tech related shit that way before
